modLoader="javafml"
loaderVersion="[40,)"
license="All Rights Reserved"

[[mods]]
modId="irronet"
version="1.0.0"
displayName="Irronet"
credits="Twitch.tv/rasgajag"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="Rasgajag"

[[dependencies.irronet]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




